---
zombie_file: "test_zombies.csv"
zombie_text: |
  h1. {name}

  p=. !{{width:450px;height=300px}}{image_file}!

  *What is your CAT IRC handle?*

  *What is your CAT account name?*

  *What fun stuff do you do?*

  *What do you study?*

  *Do you work or volunteer?*

  *A fun fact about yourself that you want us to know:*

  *Link to photos, websites, etc. that describe you (please keep appropriate):*

roster_line: "| [[{username}]] | irc handle goes here!! | {name} | !{{width:450px;height=300px}}{host}/attachments/download/xxxx/{image_file}! |\n"
