---
zombie_file: "example_zombies.csv"
zombie_text: |
  h1. {name}

  p=. !{{width:450px;height=300px}}{username}.jpg!

  *What is your CAT IRC handle?*

  *What is your CAT account name?*

  *What brought you to the CAT?*

  *What are you currently working on?*

  *Tell us an interesting non-CAT-related thing about you:*

roster_line: "| [[{username}]] | irc handle goes here!! | {name} | !{{width:450px;height=300px}}{username}_IMAGE_HERE! |\n"
